export const dummyDeck = [
  {
    id: 1,
    name: "test",
    attack_power: 1,
    cost: 1,
    dominance: 1,
    types: ["earth"],
    actions: ["farm", "fight"],
  },
  {
    id: 2,
    name: "test2",
    attack_power: 3,
    cost: 2,
    dominance: 2,
    types: ["water"],
    actions: ["buy", "farm"],
  },
  {
    id: 3,
    name: "test",
    attack_power: 1,
    cost: 1,
    dominance: 1,
    types: ["earth"],
    actions: ["farm", "fight"],
  },
  {
    id: 4,
    name: "test2",
    attack_power: 3,
    cost: 2,
    dominance: 2,
    types: ["water"],
    actions: ["buy", "farm"],
  },
  {
    id: 5,
    name: "test",
    attack_power: 1,
    cost: 1,
    dominance: 1,
    types: ["earth"],
    actions: ["farm", "fight"],
  },
  {
    id: 6,
    name: "test2",
    attack_power: 3,
    cost: 2,
    dominance: 2,
    types: ["water"],
    actions: ["buy", "farm"],
  },
  {
    id: 7,
    name: "test",
    attack_power: 1,
    cost: 1,
    dominance: 1,
    types: ["earth"],
    actions: ["farm", "fight"],
  },
  {
    id: 8,
    name: "test2",
    attack_power: 3,
    cost: 2,
    dominance: 2,
    types: ["water"],
    actions: ["buy", "farm"],
  },
];
